spring:
  http:
    encoding:
      enabled: true
      charset: utf-8
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite::resource:data/laxi.db
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 12000
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-test-query: select 1
      validation-timeout: 5000
      minimum-idle: 5
      maximum-pool-size: 10
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
    default-property-inclusion: non_null
    time-zone: GMT+8
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss